#!/bin/bash

WATERFOX_BROWSER=$( wget -S --spider -q --max-redirect=0 https://cdn1.waterfox.net/waterfox/releases/latest/linux 2>&1 | grep -i -e "location" -e "linux"  | awk '{print $2}' | tr -d '\n')

wget -q --show-progress "$WATERFOX_BROWSER"

WATERFOX=$(ls waterfox-* | sed -E 's/([^-]+)-([0-9.]+)\..*/\1 \2/')
NAME=$(echo $WATERFOX | awk '{print $1}')
VERSION=$(echo $WATERFOX | awk '{print $2}')
ARCH="amd64"
WORK_DIR="$NAME-$VERSION-$ARCH"

mkdir -p $WORK_DIR/{lib,usr/{bin,share/applications,icons/hicolor/scalable/apps}}
cp -r DEBIAN/ $WORK_DIR/
cp waterfox.desktop $WORK_DIR/usr/share/applications/
tar -xvjf waterfox-*.tar.bz2 -C $WORK_DIR/lib/
ln -s ../../lib/waterfox/waterfox $WORK_DIR/usr/bin/waterfox

wget -q --show-progress https://raw.githubusercontent.com/BrowserWorks/website/refs/heads/main-ssg/public/images/waterfox-icon.svg -P $WORK_DIR/usr/share/icons/hicolor/scalable/apps/

SIZE_WATERFOX=$(du -ks $WORK_DIR)
sed -i "s/NAME_PACKAGE/$NAME/g" $WORK_DIR/DEBIAN/control
sed -i "s/VERSION_PACKAGE/$VERSION/g" $WORK_DIR/DEBIAN/control
sed -i "s/ARCH_PACKAGE/$ARCH/g" $WORK_DIR/DEBIAN/control
sed -i "s/SIZE_PACKAGE/$SIZE_WATERFOX/g" $WORK_DIR/DEBIAN/control

sed -i "s/NAME_PACKAGE/$NAME/g" $WORK_DIR/usr/share/applications/waterfox.desktop
sed -i "s/VERSION_PACKAGE/$VERSION/g" $WORK_DIR/usr/share/applications/waterfox.desktop

dpkg-deb --build $WORK_DIR
